# Ubuntu latest
# FROM kirstlab/asc_seurat:dynverse_v2.2
FROM winuthayanon/asc_seurat:20230530
LABEL Maintainer="Sarayut (Nine) Winuthayanon, https://www.linkedin.com/in/winuthayanons/"
SHELL ["/bin/bash", "-c"]

# Set workdir
WORKDIR /app

 # Get server files
COPY ui.R /app/ui.R
COPY /scripts/bscripts/init_app.sh /app/init_app.sh

# expose port
EXPOSE 3838

# Fix permissions
RUN chmod a+rwx -R /app/*
RUN chmod a+rwx -R /app

# Init image
CMD /app/init_app.sh

